import { Locale, getLocale } from "@taxilao/shared";

const en = {
  premium: "Premium",
  verified: "Verified",
  available: "Available",
  driver: "Driver",
  drivers: "Drivers",
  bookDriver: "Book driver",
  details: "Details",
  startingPrice: "Starting price",
  city: "City",
  rating: "Rating",
  vehicle: "Vehicle",
  routes: "Accepted routes",
  languages: "Languages",
  contact: "Contact",
  reviews: "reviews",
  viewDrivers: "View drivers",
  allTours: "All tours",
  bookTour: "Book this tour",
  tourPackages: "Tour packages",
  toursTitle: "Private tours with premium drivers",
  toursLead: "City tours, day trips, multi-day journeys, and custom routes across Laos.",
  marketplace: "Driver marketplace",
  availableDrivers: "Drivers ready to serve",
  items: "items",
  filter: "Filter",
  filterList: "Filter drivers",
  allCities: "All cities",
  allLanguages: "All languages",
  type: "Type",
  everyone: "All drivers",
  allRatings: "All ratings",
  applyFilter: "Apply filters",
  clearFilter: "Clear filters",
  foundDrivers: "drivers found",
  scrollList: "Scroll to view",
  customRoute: "Custom route available",
  bookingEyebrow: "TAXILAO BOOKING",
  bookingTitle: "Call a taxi or book a driver",
  bookingLead: "Enter your pickup, destination, and contact details to send a booking.",
  stepPickup: "1. Choose pickup",
  stepDropoff: "2. Choose destination",
  stepConfirm: "3. Confirm contact",
  quickBooking: "Quick booking",
  callTaxi: "Call TAXILAO",
  noLoginNeeded: "No login required. Enter the essential details and send your booking.",
  pickup: "Pickup location",
  dropoff: "Destination",
  contactField: "Phone or email",
  meterDetails: "Meter pricing details",
  meterText: "Rate per km: {rate}. Minimum fare: {minimum}. Longer routes are calculated by distance.",
  example: "Example",
  comment: "Comments",
  commentPlaceholder: "Message for the driver, flight number, hotel, or luggage details...",
  moreSettings: "More options",
  customerName: "Customer name",
  optional: "Optional",
  selectDriver: "Choose driver",
  availableDriver: "Any available driver",
  tourPackage: "Tour package",
  regularRide: "Regular taxi",
  sending: "Sending...",
  confirmBooking: "Confirm booking",
  bookingSending: "Sending your booking...",
  bookingSuccess: "Booking successful. Booking ID",
  bookingFailed: "Unable to submit booking",
  trackBooking: "Track booking",
  member: "Member",
  signIn: "Sign in",
  customerProfile: "Customer profile",
  tripHistory: "Trip history",
  bookingStatus: "Booking status",
  logout: "Sign out",
  loginTitle: "Sign in to your member account",
  loginLead: "View booking history, track rides, and make your next booking faster.",
  loginGoogle: "Sign in with Google",
  loginGoogleLead: "Use your Google account to register or sign in.",
  continueGoogle: "Continue with Google",
  passwordNote: "TAXILAO never sees or stores your Google password.",
  accountVerified: "Verified account",
  accountInfo: "Account information",
  accountId: "Account ID",
  accountIdHelp: "Use this ID when contacting support or when an admin searches for your account.",
  copyId: "Copy ID",
  copied: "Copied",
  trips: "Trips",
  completed: "Completed",
  active: "In progress",
  total: "Total",
  status: "Status",
  joined: "Joined",
  loginMethod: "Login method",
  noTrips: "No trip history yet",
  noActiveTrips: "No trips are currently in progress",
  tripsAppear: "Your bookings will appear here.",
  dashboardTitle: "Track your booking",
  dashboardLead: "View status, driver, and trip details.",
  myBookings: "My bookings",
  searchBooking: "Find booking",
  guestBooking: "For bookings made without signing in",
  phone: "Phone / WhatsApp",
  searching: "Searching...",
  search: "Search",
  refresh: "Refresh status",
  route: "Route",
  dateTime: "Date and time",
  price: "Price",
  noDriver: "A driver has not been assigned yet.",
  pending: "Pending confirmation",
  confirmed: "Confirmed",
  onTheWay: "Driver is on the way",
  cancelled: "Cancelled",
  applyTitle: "Apply for TAXILAO verification",
  becomeDriver: "Become a driver",
  name: "Name",
  documents: "Documents",
  submitApplication: "Submit application",
  submitting: "Submitting...",
  noDate: "Not scheduled",
  applicationSending: "Sending application...",
  applicationSuccess: "Application submitted. Driver ID",
  applicationFailed: "Unable to submit application",
  useCurrentLocation: "Use current location",
  locating: "Locating...",
  searchPlace: "Search for a place",
  noPlaces: "No matching places found",
  calculatingRoute: "Calculating route...",
  routeDistance: "Distance",
  routeEta: "Estimated time",
  routePrice: "Estimated fare",
  chooseLocations: "Choose pickup and destination from the search results",
  locationDenied: "Unable to access your current location",
  routeFailed: "Unable to calculate this route",
  selectOnMap: "Choose on map",
  moveMapHint: "Move and rotate the map until the pin is exactly at the location",
  confirmLocation: "Confirm this location",
  pricingMethod: "Choose pricing method",
  fixedPrice: "System fixed price",
  fixedPriceHelp: "Pay the displayed estimate for this route",
  meterPrice: "Meter price",
  meterPriceHelp: "Final fare uses the actual distance and time",
  meterEstimated: "Estimated meter fare",
  meterNoticeTitle: "Meter pricing terms",
  meterNoticeText: "Starting fare {base} includes the first {included} km. After that: {rate}/km plus {minute}/minute. The amount shown before booking is only an estimate; the final fare follows the actual meter.",
  meterAccept: "I understand and accept meter pricing",
  meterCancel: "Close",
  meterConfirm: "Accept meter pricing",
  estimatedLabel: "Estimated",
  taxiFixedPricing: "Regular taxi uses the system price",
  taxiFixedPricingHelp: "A driver is assigned after booking. The displayed route estimate is the booking price.",
  driverMeterPricing: "Driver booking uses meter pricing",
  driverMeterPricingHelp: "When you choose a specific driver, the final fare follows actual distance and time.",
  driverReservation: "Driver reservation",
  bookSelectedDriver: "Reserve a driver",
  driverReservationLead: "Choose a driver and pickup point. The destination is optional and can be agreed with the driver.",
  optionalDestination: "Optional destination",
  findingDriver: "Finding a driver",
  findingDriverHelp: "Your request is being sent to available drivers nearby.",
  waitingForDriver: "Waiting for a driver to accept",
  driverAccepted: "Driver accepted your ride",
  driverComing: "Your driver is on the way",
  tripStarted: "Your trip has started",
  tripCompleted: "Trip completed",
  requestCancelled: "Ride request cancelled",
  liveStatus: "Live ride status",
  rideRequestId: "Ride request ID",
  viewTripDetails: "View trip details",
  realtimeConnected: "Live updates connected",
  realtimeReconnecting: "Reconnecting live updates...",
  driverLiveLocation: "Driver live location",
  gpsWaiting: "Waiting for the driver's GPS signal",
  gpsUpdated: "GPS updated",
  memberOnly: "Members only",
  loginBeforeBooking: "Sign in before calling a taxi",
  loginBeforeBookingHelp: "Create or sign in to your member account to book, track your ride, and keep your trip history.",
  checkingAccount: "Checking your account...",
  accountBookingSafety: "Your booking will be linked securely to your member account",
  liveChat: "Live chat",
  noChatMessages: "No messages yet",
  typeMessage: "Type a message...",
  chatAfterAccepted: "Chat opens after a driver accepts your ride.",
  cancelRide: "Cancel ride",
  cancelRideConfirm: "Cancel this ride request?",
  stayOnTracker: "Stay on this screen while TAXILAO finds your driver."
} as const;

type UiCopy = { [K in keyof typeof en]: string };

const lo: UiCopy = {
  premium: "ພຣີມຽມ", verified: "ຢືນຢັນແລ້ວ", available: "ພ້ອມບໍລິການ", driver: "ຄົນຂັບ", drivers: "ຄົນຂັບ",
  bookDriver: "ຈອງຄົນຂັບ", details: "ລາຍລະອຽດ", startingPrice: "ລາຄາເລີ່ມຕົ້ນ", city: "ເມືອງ", rating: "ຄະແນນ",
  vehicle: "ລົດ", routes: "ເສັ້ນທາງທີ່ຮັບ", languages: "ພາສາ", contact: "ຕິດຕໍ່", reviews: "ຣີວິວ", viewDrivers: "ເບິ່ງຄົນຂັບ",
  allTours: "ທົວທັງໝົດ", bookTour: "ຈອງທົວນີ້", tourPackages: "ແພັກເກດທົວ", toursTitle: "ທົວສ່ວນຕົວກັບຄົນຂັບພຣີມຽມ",
  toursLead: "ທົວເມືອງ, ທ່ຽວມື້ດຽວ, ຫຼາຍມື້ ແລະເສັ້ນທາງຕາມຕ້ອງການ.", marketplace: "ຕະຫຼາດຄົນຂັບ",
  availableDrivers: "ຄົນຂັບທີ່ພ້ອມໃຫ້ບໍລິການ", items: "ລາຍການ", filter: "ຕົວກອງ", filterList: "ກອງລາຍຊື່",
  allCities: "ທຸກເມືອງ", allLanguages: "ທຸກພາສາ", type: "ປະເພດ", everyone: "ທຸກຄົນ", allRatings: "ທຸກຄະແນນ",
  applyFilter: "ກອງຂໍ້ມູນ", clearFilter: "ລ້າງຕົວກອງ", foundDrivers: "ຄົນຂັບທີ່ພົບ", scrollList: "ເລື່ອນເບິ່ງລາຍການ",
  customRoute: "ຮັບເສັ້ນທາງຕາມຕ້ອງການ", bookingEyebrow: "TAXILAO BOOKING", bookingTitle: "ເອີ້ນລົດ ຫຼື ຈອງຄົນຂັບ",
  bookingLead: "ໃສ່ສະຖານທີ່ຮັບ, ສະຖານທີ່ໄປ ແລະຂໍ້ມູນຕິດຕໍ່ເພື່ອສົ່ງການຈອງ.", stepPickup: "1. ເລືອກຈຸດຮັບ",
  stepDropoff: "2. ເລືອກຈຸດໄປ", stepConfirm: "3. ຢືນຢັນຂໍ້ມູນຕິດຕໍ່", quickBooking: "ຈອງລົດດ່ວນ", callTaxi: "ເອີ້ນລົດ TAXILAO",
  noLoginNeeded: "ບໍ່ຕ້ອງລັອກອິນ. ໃສ່ຂໍ້ມູນຫຼັກແລ້ວສົ່ງການຈອງໄດ້ເລີຍ.", pickup: "ສະຖານທີ່ໄປຮັບ",
  dropoff: "ສະຖານທີ່ໄປສົ່ງ", contactField: "ເບີ ຫຼື ເມລ", meterDetails: "ລາຍລະອຽດຄິດເງິນຕາມ meter",
  meterText: "ກິໂລລະ {rate}. ຂັ້ນຕ່ຳ {minimum}. ເສັ້ນທາງໄກຄິດຕາມກິໂລ.", example: "ຕົວຢ່າງ", comment: "ເນື້ອຫາຄຳເຫັນ",
  commentPlaceholder: "ຂໍ້ຄວາມຫາຄົນຂັບ, ເລກຖ້ຽວບິນ, ໂຮງແຮມ ຫຼືກະເປົາ...", moreSettings: "ຕັ້ງຄ່າເພີ່ມເຕີມ",
  customerName: "ຊື່ລູກຄ້າ", optional: "ບໍ່ບັງຄັບ", selectDriver: "ເລືອກຄົນຂັບ", availableDriver: "ຄົນຂັບທີ່ວ່າງ",
  tourPackage: "ແພັກເກດທົວ", regularRide: "ເອີ້ນລົດທົ່ວໄປ", sending: "ກຳລັງສົ່ງ...", confirmBooking: "ຢືນຢັນການຈອງ",
  bookingSending: "ກຳລັງສົ່ງການຈອງ...", bookingSuccess: "ຈອງສຳເລັດ. Booking ID", bookingFailed: "ສົ່ງການຈອງບໍ່ສຳເລັດ",
  trackBooking: "ຕິດຕາມການຈອງ", member: "ສະມາຊິກ", signIn: "ເຂົ້າລະບົບ", customerProfile: "ໂປຣໄຟລູກຄ້າ",
  tripHistory: "ປະຫວັດເດີນທາງ", bookingStatus: "ສະຖານະການຈອງ", logout: "ອອກຈາກລະບົບ",
  loginTitle: "ເຂົ້າສູ່ບັນຊີສະມາຊິກ", loginLead: "ເບິ່ງປະຫວັດການຈອງ, ຕິດຕາມລົດ ແລະຈອງຄັ້ງຕໍ່ໄປໄດ້ສະດວກຂຶ້ນ.",
  loginGoogle: "ເຂົ້າລະບົບດ້ວຍ Google", loginGoogleLead: "ໃຊ້ບັນຊີ Google ເພື່ອສະໝັກ ຫຼືເຂົ້າລະບົບ.",
  continueGoogle: "ສືບຕໍ່ດ້ວຍ Google", passwordNote: "TAXILAO ບໍ່ເຫັນ ແລະບໍ່ເກັບລະຫັດຜ່ານ Google ຂອງທ່ານ.",
  accountVerified: "ບັນຊີຢືນຢັນແລ້ວ", accountInfo: "ຂໍ້ມູນບັນຊີ", accountId: "ເລກໄອດີບັນຊີ",
  accountIdHelp: "ໃຊ້ ID ນີ້ເວລາຕິດຕໍ່ ຫຼືໃຫ້ແອດມິນຄົ້ນຫາບັນຊີ.", copyId: "ຄັດລອກ ID", copied: "ຄັດລອກແລ້ວ",
  trips: "ການເດີນທາງ", completed: "ສຳເລັດແລ້ວ", active: "ກຳລັງດຳເນີນ", total: "ຍອດລວມ", status: "ສະຖານະ",
  joined: "ວັນສະໝັກ", loginMethod: "ວິທີ Login", noTrips: "ຍັງບໍ່ມີປະຫວັດເດີນທາງ",
  noActiveTrips: "ຍັງບໍ່ມີການເດີນທາງທີ່ກຳລັງດຳເນີນ", tripsAppear: "ລາຍການຈອງຈະສະແດງຢູ່ນີ້.",
  dashboardTitle: "ຕິດຕາມການຈອງ", dashboardLead: "ເບິ່ງສະຖານະ, ຄົນຂັບ ແລະລາຍລະອຽດການເດີນທາງ.",
  myBookings: "ລາຍການຈອງຂອງຂ້ອຍ", searchBooking: "ຄົ້ນຫາ Booking", guestBooking: "ສຳລັບການຈອງແບບບໍ່ໄດ້ Login",
  phone: "ເບີໂທ / WhatsApp", searching: "ກຳລັງຄົ້ນຫາ...", search: "ຄົ້ນຫາ", refresh: "ໂຫຼດສະຖານະໃໝ່",
  route: "ເສັ້ນທາງ", dateTime: "ວັນເວລາ", price: "ລາຄາ", noDriver: "ຍັງບໍ່ໄດ້ມອບຄົນຂັບ.",
  pending: "ລໍຖ້າຢືນຢັນ", confirmed: "ຢືນຢັນແລ້ວ", onTheWay: "ຄົນຂັບກຳລັງໄປ", cancelled: "ຍົກເລີກ",
  applyTitle: "ສະໝັກຮັບການຢືນຢັນ TAXILAO", becomeDriver: "ສະໝັກເປັນຄົນຂັບ", name: "ຊື່", documents: "ເອກະສານ",
  submitApplication: "ສົ່ງໃບສະໝັກ", submitting: "ກຳລັງສົ່ງ...", noDate: "ຍັງບໍ່ກຳນົດເວລາ",
  applicationSending: "ກຳລັງສົ່ງໃບສະໝັກ...", applicationSuccess: "ສົ່ງໃບສະໝັກສຳເລັດ. Driver ID",
  applicationFailed: "ສົ່ງໃບສະໝັກບໍ່ສຳເລັດ",
  useCurrentLocation: "ໃຊ້ຕຳແໜ່ງປັດຈຸບັນ",
  locating: "ກຳລັງຊອກຫາຕຳແໜ່ງ...",
  searchPlace: "ຄົ້ນຫາສະຖານທີ່",
  noPlaces: "ບໍ່ພົບສະຖານທີ່",
  calculatingRoute: "ກຳລັງຄຳນວນເສັ້ນທາງ...",
  routeDistance: "ໄລຍະທາງ",
  routeEta: "ເວລາໂດຍປະມານ",
  routePrice: "ລາຄາໂດຍປະມານ",
  chooseLocations: "ເລືອກຈຸດຮັບ ແລະ ຈຸດສົ່ງຈາກຜົນຄົ້ນຫາ",
  locationDenied: "ບໍ່ສາມາດເຂົ້າເຖິງຕຳແໜ່ງປັດຈຸບັນ",
  routeFailed: "ບໍ່ສາມາດຄຳນວນເສັ້ນທາງນີ້ໄດ້",
  selectOnMap: "ເລືອກໃນແຜນທີ່",
  moveMapHint: "ເລື່ອນ ແລະ ໝຸນແຜນທີ່ໃຫ້ pin ກົງກັບຈຸດຈິງ",
  confirmLocation: "ຢືນຢັນຈຸດນີ້",
  pricingMethod: "ເລືອກຮູບແບບຄິດລາຄາ",
  fixedPrice: "ລາຄາຄົງທີ່ຕາມລະບົບ",
  fixedPriceHelp: "ຈ່າຍຕາມລາຄາທີ່ສະແດງສຳລັບເສັ້ນທາງນີ້",
  meterPrice: "ຄິດລາຄາຕາມ Meter",
  meterPriceHelp: "ລາຄາສຸດທ້າຍຄິດຕາມໄລຍະທາງ ແລະເວລາຈິງ",
  meterEstimated: "ລາຄາ Meter ໂດຍປະມານ",
  meterNoticeTitle: "ເງື່ອນໄຂການຄິດ Meter",
  meterNoticeText: "ລາຄາເລີ່ມຕົ້ນ {base} ລວມ {included} km ທຳອິດ. ຫຼັງຈາກນັ້ນ {rate}/km ບວກ {minute}/ນາທີ. ລາຄາກ່ອນຈອງເປັນພຽງຄ່າປະມານ; ລາຄາສຸດທ້າຍອີງຕາມ Meter ຈິງ.",
  meterAccept: "ຂ້ອຍເຂົ້າໃຈ ແລະຍອມຮັບການຄິດ Meter",
  meterCancel: "ປິດ",
  meterConfirm: "ຍອມຮັບລາຄາ Meter",
  estimatedLabel: "ໂດຍປະມານ",
  taxiFixedPricing: "ເອີ້ນ Taxi ທົ່ວໄປໃຊ້ລາຄາຕາມລະບົບ",
  taxiFixedPricingHelp: "ລະບົບຈະຈັດຄົນຂັບໃຫ້ຫຼັງຈອງ ແລະລາຄາທີ່ສະແດງແມ່ນລາຄາຈອງ.",
  driverMeterPricing: "ຈອງຄົນຂັບໃຊ້ Meter ເທົ່ານັ້ນ",
  driverMeterPricingHelp: "ເມື່ອເລືອກຄົນຂັບສະເພາະ ລາຄາສຸດທ້າຍຈະຄິດຕາມໄລຍະທາງ ແລະເວລາຈິງ.",
  driverReservation: "ຈອງຄົນຂັບ",
  bookSelectedDriver: "ເລືອກຈອງຄົນຂັບ",
  driverReservationLead: "ເລືອກຄົນຂັບ ແລະຈຸດໄປຮັບ. ຈຸດຈະໄປບໍ່ບັງຄັບ ແລະສາມາດຕົກລົງກັບຄົນຂັບໄດ້.",
  optionalDestination: "ຈຸດຈະໄປ (ບໍ່ບັງຄັບ)",
  findingDriver: "ກຳລັງຊອກຫາຄົນຂັບ",
  findingDriverHelp: "ລະບົບກຳລັງສົ່ງຄຳຂໍໄປຫາຄົນຂັບທີ່ພ້ອມຢູ່ໃກ້.",
  waitingForDriver: "ກຳລັງລໍຖ້າຄົນຂັບຮັບວຽກ",
  driverAccepted: "ຄົນຂັບຮັບການເອີ້ນລົດແລ້ວ",
  driverComing: "ຄົນຂັບກຳລັງມາຮັບທ່ານ",
  tripStarted: "ເລີ່ມການເດີນທາງແລ້ວ",
  tripCompleted: "ການເດີນທາງສຳເລັດແລ້ວ",
  requestCancelled: "ການເອີ້ນລົດຖືກຍົກເລີກ",
  liveStatus: "ສະຖານະລົດແບບລຽວທາມ",
  rideRequestId: "ເລກຄຳຂໍເອີ້ນລົດ",
  viewTripDetails: "ເບິ່ງລາຍລະອຽດການເດີນທາງ",
  realtimeConnected: "ເຊື່ອມຕໍ່ສະຖານະສົດແລ້ວ",
  realtimeReconnecting: "ກຳລັງເຊື່ອມຕໍ່ສະຖານະສົດໃໝ່...",
  driverLiveLocation: "ຕຳແໜ່ງຄົນຂັບແບບລຽວທາມ",
  gpsWaiting: "ກຳລັງລໍສັນຍານ GPS ຈາກຄົນຂັບ",
  gpsUpdated: "GPS ອັບເດດ",
  memberOnly: "ສຳລັບສະມາຊິກ",
  loginBeforeBooking: "ເຂົ້າລະບົບກ່ອນເອີ້ນລົດ",
  loginBeforeBookingHelp: "ສະໝັກ ຫຼືເຂົ້າບັນຊີສະມາຊິກເພື່ອຈອງ, ຕິດຕາມລົດ ແລະເກັບປະຫວັດການເດີນທາງ.",
  checkingAccount: "ກຳລັງກວດສອບບັນຊີ...",
  accountBookingSafety: "ການຈອງຈະຖືກເຊື່ອມກັບບັນຊີສະມາຊິກຂອງທ່ານຢ່າງປອດໄພ",
  liveChat: "ແຊັດສົດ",
  noChatMessages: "ຍັງບໍ່ມີຂໍ້ຄວາມ",
  typeMessage: "ພິມຂໍ້ຄວາມ...",
  chatAfterAccepted: "ແຊັດຈະເປີດເມື່ອຄົນຂັບຮັບງານແລ້ວ.",
  cancelRide: "ຍົກເລີກການເອີ້ນລົດ",
  cancelRideConfirm: "ຢືນຢັນຍົກເລີກການເອີ້ນລົດນີ້ບໍ?",
  stayOnTracker: "ກະລຸນາຢູ່ໜ້ານີ້ຂະນະທີ່ TAXILAO ກຳລັງຫາຄົນຂັບ."
};

const translations: Record<Locale, UiCopy> = {
  lo,
  en,
  th: { ...en, premium: "พรีเมียม", verified: "ยืนยันแล้ว", available: "พร้อมบริการ", driver: "คนขับ", drivers: "คนขับ", bookDriver: "จองคนขับ", details: "รายละเอียด", city: "เมือง", rating: "คะแนน", vehicle: "รถ", routes: "เส้นทางที่รับ", languages: "ภาษา", contact: "ติดต่อ", viewDrivers: "ดูคนขับ", allTours: "ทัวร์ทั้งหมด", bookTour: "จองทัวร์นี้", marketplace: "ตลาดคนขับ", availableDrivers: "คนขับที่พร้อมให้บริการ", filter: "ตัวกรอง", filterList: "กรองรายชื่อ", allCities: "ทุกเมือง", allLanguages: "ทุกภาษา", type: "ประเภท", everyone: "คนขับทั้งหมด", applyFilter: "ใช้ตัวกรอง", clearFilter: "ล้างตัวกรอง", bookingTitle: "เรียกรถหรือจองคนขับ", pickup: "สถานที่รับ", dropoff: "จุดหมาย", contactField: "เบอร์โทรหรืออีเมล", comment: "หมายเหตุ", moreSettings: "ตัวเลือกเพิ่มเติม", customerName: "ชื่อลูกค้า", selectDriver: "เลือกคนขับ", confirmBooking: "เรียกรถ", trackBooking: "ติดตามรถ", signIn: "เข้าสู่ระบบ", customerProfile: "โปรไฟล์ลูกค้า", tripHistory: "ประวัติการเดินทาง", bookingStatus: "สถานะการจอง", logout: "ออกจากระบบ", loginTitle: "เข้าสู่บัญชีสมาชิก", loginGoogle: "เข้าสู่ระบบด้วย Google", continueGoogle: "ดำเนินการต่อด้วย Google", accountInfo: "ข้อมูลบัญชี", accountId: "รหัสบัญชี", copyId: "คัดลอก ID", trips: "การเดินทาง", completed: "เสร็จสิ้น", active: "กำลังดำเนินการ", total: "ยอดรวม", status: "สถานะ", dashboardTitle: "ติดตามการจอง", myBookings: "การจองของฉัน", searchBooking: "ค้นหาการจอง", search: "ค้นหา", refresh: "รีเฟรชสถานะ" },
  zh: { ...en, premium: "高端", verified: "已认证", available: "可服务", driver: "司机", drivers: "司机", bookDriver: "预订司机", details: "详情", city: "城市", rating: "评分", vehicle: "车辆", routes: "服务路线", languages: "语言", contact: "联系", viewDrivers: "查看司机", allTours: "全部行程", bookTour: "预订此行程", marketplace: "司机市场", availableDrivers: "可服务司机", filter: "筛选", filterList: "筛选司机", allCities: "所有城市", allLanguages: "所有语言", type: "类型", everyone: "全部司机", applyFilter: "应用筛选", clearFilter: "清除筛选", bookingTitle: "叫车或预订司机", pickup: "上车地点", dropoff: "目的地", contactField: "电话或邮箱", comment: "备注", moreSettings: "更多选项", customerName: "客户姓名", selectDriver: "选择司机", confirmBooking: "确认预订", trackBooking: "跟踪预订", signIn: "登录", customerProfile: "客户资料", tripHistory: "行程历史", bookingStatus: "预订状态", logout: "退出登录", loginTitle: "登录会员账户", loginGoogle: "使用 Google 登录", continueGoogle: "继续使用 Google", accountInfo: "账户信息", accountId: "账户 ID", copyId: "复制 ID", trips: "行程", completed: "已完成", active: "进行中", total: "总计", status: "状态", dashboardTitle: "跟踪预订", myBookings: "我的预订", searchBooking: "查找预订", search: "搜索", refresh: "刷新状态" },
  vi: { ...en, premium: "Cao cấp", verified: "Đã xác minh", available: "Sẵn sàng", driver: "Tài xế", drivers: "Tài xế", bookDriver: "Đặt tài xế", details: "Chi tiết", city: "Thành phố", rating: "Đánh giá", vehicle: "Xe", routes: "Tuyến phục vụ", languages: "Ngôn ngữ", contact: "Liên hệ", viewDrivers: "Xem tài xế", allTours: "Tất cả tour", bookTour: "Đặt tour này", marketplace: "Danh sách tài xế", availableDrivers: "Tài xế sẵn sàng phục vụ", filter: "Bộ lọc", filterList: "Lọc tài xế", allCities: "Tất cả thành phố", allLanguages: "Tất cả ngôn ngữ", type: "Loại", everyone: "Tất cả tài xế", applyFilter: "Áp dụng", clearFilter: "Xóa bộ lọc", bookingTitle: "Gọi xe hoặc đặt tài xế", pickup: "Điểm đón", dropoff: "Điểm đến", contactField: "Điện thoại hoặc email", comment: "Ghi chú", moreSettings: "Tùy chọn khác", customerName: "Tên khách hàng", selectDriver: "Chọn tài xế", confirmBooking: "Xác nhận đặt xe", trackBooking: "Theo dõi đặt xe", signIn: "Đăng nhập", customerProfile: "Hồ sơ khách hàng", tripHistory: "Lịch sử chuyến đi", bookingStatus: "Trạng thái đặt xe", logout: "Đăng xuất", loginTitle: "Đăng nhập tài khoản thành viên", loginGoogle: "Đăng nhập bằng Google", continueGoogle: "Tiếp tục với Google", accountInfo: "Thông tin tài khoản", accountId: "Mã tài khoản", copyId: "Sao chép ID", trips: "Chuyến đi", completed: "Hoàn thành", active: "Đang thực hiện", total: "Tổng cộng", status: "Trạng thái", dashboardTitle: "Theo dõi đặt xe", myBookings: "Đặt xe của tôi", searchBooking: "Tìm đặt xe", search: "Tìm kiếm", refresh: "Cập nhật trạng thái" },
  ja: { ...en, premium: "プレミアム", verified: "認証済み", available: "利用可能", driver: "ドライバー", drivers: "ドライバー", bookDriver: "ドライバーを予約", details: "詳細", city: "都市", rating: "評価", vehicle: "車両", routes: "対応ルート", languages: "言語", contact: "連絡", viewDrivers: "ドライバーを見る", allTours: "すべてのツアー", bookTour: "このツアーを予約", marketplace: "ドライバー一覧", availableDrivers: "利用可能なドライバー", filter: "絞り込み", filterList: "ドライバーを絞り込む", allCities: "すべての都市", allLanguages: "すべての言語", type: "種類", everyone: "すべてのドライバー", applyFilter: "適用", clearFilter: "クリア", bookingTitle: "タクシーを呼ぶ・ドライバーを予約", pickup: "乗車場所", dropoff: "目的地", contactField: "電話またはメール", comment: "備考", moreSettings: "その他の設定", customerName: "お客様名", selectDriver: "ドライバーを選択", confirmBooking: "予約を確定", trackBooking: "予約を追跡", signIn: "ログイン", customerProfile: "お客様プロフィール", tripHistory: "乗車履歴", bookingStatus: "予約状況", logout: "ログアウト", loginTitle: "会員アカウントにログイン", loginGoogle: "Googleでログイン", continueGoogle: "Googleで続行", accountInfo: "アカウント情報", accountId: "アカウントID", copyId: "IDをコピー", trips: "乗車", completed: "完了", active: "進行中", total: "合計", status: "状況", dashboardTitle: "予約を追跡", myBookings: "予約一覧", searchBooking: "予約を検索", search: "検索", refresh: "状況を更新" },
  ko: { ...en, premium: "프리미엄", verified: "인증됨", available: "이용 가능", driver: "기사", drivers: "기사", bookDriver: "기사 예약", details: "상세정보", city: "도시", rating: "평점", vehicle: "차량", routes: "운행 경로", languages: "언어", contact: "연락", viewDrivers: "기사 보기", allTours: "전체 투어", bookTour: "이 투어 예약", marketplace: "기사 목록", availableDrivers: "이용 가능한 기사", filter: "필터", filterList: "기사 필터", allCities: "모든 도시", allLanguages: "모든 언어", type: "유형", everyone: "모든 기사", applyFilter: "필터 적용", clearFilter: "필터 초기화", bookingTitle: "택시 호출 또는 기사 예약", pickup: "승차 위치", dropoff: "목적지", contactField: "전화 또는 이메일", comment: "메모", moreSettings: "추가 옵션", customerName: "고객 이름", selectDriver: "기사 선택", confirmBooking: "예약 확인", trackBooking: "예약 추적", signIn: "로그인", customerProfile: "고객 프로필", tripHistory: "이용 내역", bookingStatus: "예약 상태", logout: "로그아웃", loginTitle: "회원 계정 로그인", loginGoogle: "Google로 로그인", continueGoogle: "Google로 계속", accountInfo: "계정 정보", accountId: "계정 ID", copyId: "ID 복사", trips: "이용", completed: "완료", active: "진행 중", total: "합계", status: "상태", dashboardTitle: "예약 추적", myBookings: "내 예약", searchBooking: "예약 검색", search: "검색", refresh: "상태 새로고침" }
};

Object.assign(translations.th, {
  bookingEyebrow: "เรียกรถ TAXILAO",
  bookingLead: "ระบุจุดรับ จุดหมาย และข้อมูลติดต่อเพื่อเรียกรถ",
  stepPickup: "1. เลือกจุดรับ",
  stepDropoff: "2. เลือกจุดหมาย",
  stepConfirm: "3. ยืนยันข้อมูลติดต่อ",
  quickBooking: "เรียกรถด่วน",
  callTaxi: "เรียกรถ TAXILAO",
  noLoginNeeded: "กรอกข้อมูลสำคัญแล้วส่งคำขอเรียกรถได้ทันที",
  meterDetails: "รายละเอียดค่าโดยสารตามมิเตอร์",
  meterText: "อัตราต่อกิโลเมตร {rate} ค่าโดยสารขั้นต่ำ {minimum} เส้นทางไกลคำนวณตามระยะทาง",
  example: "ตัวอย่าง",
  commentPlaceholder: "ข้อความถึงคนขับ หมายเลขเที่ยวบิน โรงแรม หรือรายละเอียดสัมภาระ...",
  optional: "ไม่บังคับ",
  availableDriver: "คนขับที่ว่าง",
  tourPackage: "แพ็กเกจทัวร์",
  regularRide: "เรียกรถทั่วไป",
  sending: "กำลังส่ง...",
  confirmBooking: "เรียกรถ",
  bookingSending: "กำลังเรียกรถ...",
  bookingSuccess: "ส่งคำขอเรียกรถสำเร็จ Booking ID",
  bookingFailed: "ไม่สามารถเรียกรถได้",
  findingDriver: "กำลังค้นหาคนขับ",
  findingDriverHelp: "ระบบกำลังส่งคำขอไปยังคนขับที่พร้อมให้บริการในบริเวณใกล้เคียง",
  waitingForDriver: "กำลังรอคนขับรับงาน",
  driverAccepted: "คนขับรับงานแล้ว",
  driverComing: "คนขับกำลังมารับคุณ",
  tripStarted: "เริ่มการเดินทางแล้ว",
  tripCompleted: "เดินทางเสร็จสิ้น",
  requestCancelled: "ยกเลิกการเรียกรถแล้ว",
  liveStatus: "สถานะการเดินทางแบบเรียลไทม์",
  rideRequestId: "รหัสเรียกรถ",
  viewTripDetails: "ดูรายละเอียดการเดินทาง",
  realtimeConnected: "เชื่อมต่อสถานะสดแล้ว",
  realtimeReconnecting: "กำลังเชื่อมต่อสถานะสดอีกครั้ง...",
  driverLiveLocation: "ตำแหน่งคนขับแบบเรียลไทม์",
  gpsWaiting: "กำลังรอสัญญาณ GPS จากคนขับ",
  gpsUpdated: "อัปเดต GPS"
});

Object.assign(translations.zh, {
  bookingEyebrow: "TAXILAO 预订",
  bookingLead: "输入上车地点、目的地和联系方式即可提交预订。",
  stepPickup: "1. 选择上车地点",
  stepDropoff: "2. 选择目的地",
  stepConfirm: "3. 确认联系方式",
  quickBooking: "快速预订",
  callTaxi: "呼叫 TAXILAO",
  noLoginNeeded: "无需登录。填写必要信息即可提交预订。",
  meterDetails: "计价器收费详情",
  meterText: "每公里 {rate}，最低收费 {minimum}。较长路线按距离计算。",
  example: "示例",
  commentPlaceholder: "给司机的留言、航班号、酒店或行李信息...",
  optional: "选填",
  availableDriver: "任意可用司机",
  tourPackage: "旅游套餐",
  regularRide: "普通叫车",
  sending: "正在提交...",
  bookingSending: "正在提交预订...",
  bookingSuccess: "预订成功，预订 ID",
  bookingFailed: "无法提交预订"
});

Object.assign(translations.vi, {
  bookingEyebrow: "ĐẶT XE TAXILAO",
  bookingLead: "Nhập điểm đón, điểm đến và thông tin liên hệ để gửi yêu cầu đặt xe.",
  stepPickup: "1. Chọn điểm đón",
  stepDropoff: "2. Chọn điểm đến",
  stepConfirm: "3. Xác nhận liên hệ",
  quickBooking: "Đặt xe nhanh",
  callTaxi: "Gọi TAXILAO",
  noLoginNeeded: "Không cần đăng nhập. Điền thông tin cần thiết và gửi yêu cầu đặt xe.",
  meterDetails: "Chi tiết giá cước theo đồng hồ",
  meterText: "Giá mỗi km {rate}. Giá tối thiểu {minimum}. Tuyến dài được tính theo khoảng cách.",
  example: "Ví dụ",
  commentPlaceholder: "Lời nhắn cho tài xế, số chuyến bay, khách sạn hoặc hành lý...",
  optional: "Không bắt buộc",
  availableDriver: "Tài xế đang rảnh",
  tourPackage: "Gói tour",
  regularRide: "Gọi xe thông thường",
  sending: "Đang gửi...",
  bookingSending: "Đang gửi yêu cầu đặt xe...",
  bookingSuccess: "Đặt xe thành công. Booking ID",
  bookingFailed: "Không thể gửi yêu cầu đặt xe"
});

Object.assign(translations.ja, {
  bookingEyebrow: "TAXILAO 予約",
  bookingLead: "乗車場所、目的地、連絡先を入力して予約を送信してください。",
  stepPickup: "1. 乗車場所を選択",
  stepDropoff: "2. 目的地を選択",
  stepConfirm: "3. 連絡先を確認",
  quickBooking: "クイック予約",
  callTaxi: "TAXILAOを呼ぶ",
  noLoginNeeded: "ログイン不要です。必要事項を入力して予約を送信できます。",
  meterDetails: "メーター料金の詳細",
  meterText: "1kmあたり {rate}、最低料金 {minimum}。長距離は走行距離で計算されます。",
  example: "例",
  commentPlaceholder: "ドライバーへのメッセージ、便名、ホテル、荷物の詳細...",
  optional: "任意",
  availableDriver: "空いているドライバー",
  tourPackage: "ツアーパッケージ",
  regularRide: "通常のタクシー",
  sending: "送信中...",
  bookingSending: "予約を送信しています...",
  bookingSuccess: "予約が完了しました。予約ID",
  bookingFailed: "予約を送信できませんでした"
});

Object.assign(translations.ko, {
  bookingEyebrow: "TAXILAO 예약",
  bookingLead: "승차 위치, 목적지, 연락처를 입력하여 예약을 요청하세요.",
  stepPickup: "1. 승차 위치 선택",
  stepDropoff: "2. 목적지 선택",
  stepConfirm: "3. 연락처 확인",
  quickBooking: "빠른 예약",
  callTaxi: "TAXILAO 호출",
  noLoginNeeded: "로그인이 필요하지 않습니다. 필수 정보를 입력하고 예약을 전송하세요.",
  meterDetails: "미터 요금 안내",
  meterText: "km당 {rate}, 최소 요금 {minimum}. 장거리 노선은 거리에 따라 계산됩니다.",
  example: "예시",
  commentPlaceholder: "기사에게 보낼 메시지, 항공편 번호, 호텔 또는 수하물 정보...",
  optional: "선택 사항",
  availableDriver: "이용 가능한 기사",
  tourPackage: "투어 패키지",
  regularRide: "일반 택시",
  sending: "전송 중...",
  bookingSending: "예약을 전송하고 있습니다...",
  bookingSuccess: "예약이 완료되었습니다. 예약 ID",
  bookingFailed: "예약을 전송할 수 없습니다"
});

export function getUiCopy(locale?: string): UiCopy {
  return translations[getLocale(locale)];
}

export function formatUi(template: string, values: Record<string, string>) {
  return Object.entries(values).reduce((text, [key, value]) => text.replace(`{${key}}`, value), template);
}
