name: taxilao_driver
description: TAXILAO driver app for accepting taxi jobs and sending live GPS.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^18.0.1
  flutter_map: ^7.0.2
  geolocator: ^13.0.2
  geolocator_android: ^4.6.2
  http: ^1.2.2
  latlong2: ^0.9.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/new_order.wav
    - assets/sounds/order_accepted.wav
    - assets/sounds/auto_accepted.wav
